name: safedocs

services:
  app:
    build: .
    image: safedocs-app:latest
    container_name: safedocs_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://safedocs_pg:5432/safe_docs_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-huzaifanaseer074@gmail.com}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-fnehwdpmjtdxniro}
    ports:
      - "127.0.0.1:18084:8080"
    depends_on:
      - postgres
    networks: [ app_network ]
  postgres:
    image: postgres:16-alpine
    container_name: safedocs_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: safe_docs_db
      PGDATA: /var/lib/postgresql/data/pgdata
    # No external port mapping to avoid collision; internal-only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: init scripts if you need them later
      # - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks: [ app_network ]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
